import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="relative min-h-screen bg-gray-900 flex items-center justify-center"
      >
        <Navbar />
        <main className="relative z-10">
          {children}
          {/* <ToastContainer /> */}
        </main>
         <Footer />
      </body>
    </html>
  );
}
